   name: Deploy to VM

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest
       environment: prod

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Install sshpass
         run: sudo apt-get install -y sshpass

       - name: Copy repository to VM
         run: |
           sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }}:/var/www/prepity

       - name: Build the project on VM
         run: |
           sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} 'cd /var/www/prepity && yarn install && npm run build'

       - name: Restart PM2 process
         run: |
           sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} 'pm2 restart prepity'